# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest
  name: 'Default'
  demands: []

variables:
  buildConfiguration: 'Release'
  imageName: 'meuprojeto'

steps:
# 1. Restaurar dependências
- task: UseDotNet@2
  inputs:
    version: '8.x' # Usando .NET 8

- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: '**/*.csproj'

# 2. Build do Projeto
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    arguments: '--configuration $(buildConfiguration)'

# 3. Testes Unitários
- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: '**/*.Tests.csproj'
    arguments: '--configuration $(buildConfiguration) --logger trx'

# 4. Construção da Imagem Docker
- task: Docker@2
  inputs:
    containerRegistry: 'solar'
    repository: 'teste'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: |
      $(Build.BuildId)
      latest

# 5. Publicar Artefatos
- publish: $(System.DefaultWorkingDirectory)
  artifact: 'drop'